version: '3.8'
# сервис для nginx
services:
  nginx:
    image: nginx:latest 
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80" 
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
