version: '3'
# сервис для nginx
services:
  nginx:
    image: nginx:latest #latest для последней версии 
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "127.0.0.1:8876:80" # 8876 мой порт (localhost) , 80 внутрений порт nginx
    depends_on:
      - app
    container_name: nginx

  app:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: app
    
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgres
    # ports:
    #   - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: first_project
    container_name: db

  redis:
    image: redis:latest
    command: redis-server --appendonly yes 
    volumes:
    - ./data/redis:/data
    # ports:
    #   - "127.0.0.1:8002:6379"
    container_name: redis
